# Generated by Buildr 1.4.2, change to your liking
# Version number for this release
VERSION_NUMBER = "1.0.0"
# Group identifier for your projects
GROUP = "scala-playground"
COPYRIGHT = ""

ENV['M2_REPO'] = File.join(File.dirname(__FILE__), 'vendor/m2')

require 'buildr/scala'

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://www.ibiblio.org/maven2/"

desc "The Scala-playground project"
define "scala-playground", :version => '0.001' do
  package :jar
  project.version = VERSION_NUMBER
  project.group = GROUP
  manifest["Implementation-Vendor"] = COPYRIGHT
end
